name: JSON-LD Perf Smoke

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  perf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [internal, jsonld_ex]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26'

      - name: Deps + compile
        run: |
          mix deps.get
          mix compile

      - name: Run JSON-LD microbench (backend=${{ matrix.backend }})
        id: bench
        run: |
          OUT=$(mix spec.perf.jsonld --dir . --glob '**/*.md' --repeat 1 --backend ${{ matrix.backend }} --telemetry true)
          echo "$OUT"
          echo "out=$OUT" >> $GITHUB_OUTPUT

      - name: Summarize
        run: |
          echo "### Backend ${{ matrix.backend }}" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.bench.outputs.out }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

